### ISSUE TITLE
Konnectors requires Node 4

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#263]
The `imagemagick-stream` was [recently updated](https://github.com/cozy-labs/konnectors/commit/5c52478ba2735ab3ae7aace79ff0a1c2646e043d) and it seems that this version requires Node 4. 

Users of Node 0.10 get the following error message, wich prevent the application to start:
```
/usr/local/cozy/apps/konnectors/node_modules/imagemagick-stream/index.js:3
const spawn = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/cozy/apps/konnectors/build/server/lib/google_contact_helper.js:6:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

As lot of users still use Node 0.10, maybe should we consider downgrading `imagemagick-stream`.

**Comment by frankrousseau** [comment]
Fixed with latest release.

**Comment by nicofrand** [comment]
A user (Gilles77) reported the same issue today.

**Comment by nicofrand** [comment]
Issue came back with the merge of this PR : https://github.com/cozy-labs/konnectors/pull/412

**Comment by nicofrand** [comment]
The fix was https://github.com/cozy-labs/konnectors/commit/fc91e5318312d0b44095b476769a127aaf808756
