### ISSUE TITLE
[withing] Cannot read property 'measuregrps' of undefined

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#346]
Error seen in logs:
```
/usr/local/cozy/apps/konnectors/node_modules/konnectors/build/server/konnectors/withings.js:227
            return saveBodyMeasures(measures.body.measuregrps, function(err) {
                                                 ^

TypeError: Cannot read property 'measuregrps' of undefined
    at Request._callback (/usr/local/cozy/apps/konnectors/node_modules/konnectors/build/server/konnectors/withings.js:227:50)
    at Request.self.callback (/usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Ping @frankrousseau

**Comment by frankrousseau** [comment]
Thx for reporting.

**Comment by clochix** [comment]
For the record, here's the server answer:
```
{"status":246,"error":"246"}
```
I don't find this error code [inside API documentation](http://oauth.withings.com/api/doc).

**Comment by ZeHiro** [comment]
Should be fixed with : 
https://github.com/cozy-labs/konnectors/pull/350

**Comment by clochix** [comment]
cf #350 : this PR prevent application to crash, but doesn't fix the root cause of the error: user is still unable to import its data.

**Comment by nicofrand** [comment]
Moved to https://github.com/cozy-labs/konnectors/issues/352
